baseURL: https://assadahmed.netlify.app/
languageCode: en-us
title: Portfolio for Assad Ahmed
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Explore
    subtitle: |-
      Example Portfolio Of Data Science Projects.
    title: Assad Ahmed, Investment Associate
  blog: {}
  contact:
#    address:
#        city: WY
#        country: United Kingdom
#        street: 
#        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: assad139@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (+44) 07413 001 587
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
#    copyright: Company Name
    enable: yes
    quicklinks:
#      - alt: HTML5 UP
#        text: 'Design: '
#        url: https://www.html5up.net
    social:
#      - icon: fa-twitter
#        label: Twitter
#        url: https://www.twitter.com
#      - icon: fa-facebook
#        label: Facebook
#        url: https://www.facebook.com
#      - icon: fa-instagram
#        label: Instagram
#        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/AssadAhmed/
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/massadahmed/
  image: ''
  name: Assad Ahmed
  navigation:
    button1:
      - name: See Projects
        url: blogs
    button2:
      - name: Home
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: blogs
        url: blogs
#      - name: Generic Blog
#        url: blogs/ipsum
#      - name: Elements
#        url: elements.html
    menu: Menu
    subtitle: By Assad Ahmed
    title: Portfolio
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: Project Analysing Risk-Return of DJIA stocks
        title: Risk-Return 
        url: blogs/risk_return
      - image: escalator.jpg
        subtitle: Predicting Bedechel Test Results using ML
        title: Machine Learning
        url: blogs/machine_learning
      - image: doorway.jpg
        subtitle: Mapping locations of crimes committed in London
        title: Geospatial Data Analysis
        url: blogs/crime_map
      - image: acropolis.jpg
        subtitle: Flexdashboard with Gapminder
        title: Flexdashbaord
        url: blogs/flexdashboard
      - image: clouds.jpg
        subtitle: Modelling porfolio's of stockes based on historic returns
        title: Portfolio Growth & CAPM
        url: blogs/portfolio_capm
#     - image: pic10.jpg
#        subtitle: Placeholder3
#        title: Placeholder3
#        url: blogs/ipsum
  two:
    buttonText: See Projects
    enable: yes
    subtitle: "I am a Mathematics & Physics Graduate with a Masters in Finance, 
    currently working within the Alternative Investment Management industry. This website is desgn to showcase
    some of the quantitative projects i have worked on using open source data."
    title: Overview
    url: blogs
markup: 
  goldmark: 
    renderer: 
      unsafe: true